INSERT INTO tb_estadio (descricao) VALUES ('OLÍMPICO LUJNIKI');
INSERT INTO tb_estadio (descricao) VALUES ('ECATERIMBURGO');
INSERT INTO tb_estadio (descricao) VALUES ('SÃO PETERSBURGO');
INSERT INTO tb_estadio (descricao) VALUES ('OLÍMPICO DE SOCHI');
INSERT INTO tb_estadio (descricao) VALUES ('ARENA KAZAN');
INSERT INTO tb_estadio (descricao) VALUES ('SARANSK');
INSERT INTO tb_estadio (descricao) VALUES ('SPARTAK');
INSERT INTO tb_estadio (descricao) VALUES ('KALININGRADO ');
INSERT INTO tb_estadio (descricao) VALUES ('SAMARA');
INSERT INTO tb_estadio (descricao) VALUES ('ROSTOV');
INSERT INTO tb_estadio (descricao) VALUES ('NIZHNY NOVGOROD');
INSERT INTO tb_estadio (descricao) VALUES ('VOLGOGRADO');